@CleanAuth.Api_HostAddress = http://localhost:8080


POST {{CleanAuth.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "userName": "DefaultUser",
    "password": "securePass"
}

###

POST {{CleanAuth.Api_HostAddress}}/api/auth/logout
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsIm5iZiI6MTcyNzQ1NjYwNiwiZXhwIjoxNzI3NDU3MjA2LCJpc3MiOiJDbGVhbk5ldF9BUEkiLCJhdWQiOiJDbGVhbk5ldF9BUEkifQ.A1pzMIvEHTmp7ZHWnQfE9Q_0t_22TAzCdyP3xAMQJec

###
